CREATE TABLE pessoas
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome            VARCHAR(100)                            NOT NULL,
    cpf             VARCHAR(15)                             NOT NULL,
    data_nascimento DATE                                    NOT NULL,
    telefone        VARCHAR(20)                             NOT NULL,
    email           VARCHAR(100)                            NOT NULL,
    CONSTRAINT pk_pessoas PRIMARY KEY (id)
);

CREATE TABLE clientes
(
    pessoa_id     BIGINT NOT NULL,
    data_cadastro DATE   NOT NULL,
    CONSTRAINT pk_clientes PRIMARY KEY (pessoa_id)
);

CREATE TABLE cargos
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    cargo   VARCHAR(255)                            NOT NULL,
    salario DECIMAL(10, 2)                          NOT NULL,
    CONSTRAINT pk_cargos PRIMARY KEY (id)
);

CREATE TABLE funcionarios
(
    pessoa_id     BIGINT       NOT NULL,
    data_admissao DATE         NOT NULL,
    cargo_id      BIGINT       NOT NULL,
    crmv          VARCHAR(255),
    CONSTRAINT pk_funcionarios PRIMARY KEY (pessoa_id)
);

CREATE TABLE animais
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome            VARCHAR(50)                             NOT NULL,
    especie         VARCHAR(255)                            NOT NULL,
    porte           VARCHAR(255)                            NOT NULL,
    raca            VARCHAR(50)                             NOT NULL,
    sexo            VARCHAR(255)                            NOT NULL,
    cor             VARCHAR(15),
    peso            DOUBLE PRECISION                        NOT NULL,
    castrado        BOOLEAN                                 NOT NULL,
    data_nascimento DATE                                    NOT NULL,
    observacao      VARCHAR(255),
    cliente_id      BIGINT,
    CONSTRAINT pk_animais PRIMARY KEY (id)
);

CREATE TABLE servicos
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tipo           VARCHAR(255)                            NOT NULL,
    veterinario_id BIGINT                                  NOT NULL,
    valor          DECIMAL(10, 2)                          NOT NULL,
    CONSTRAINT pk_servicos PRIMARY KEY (id)
);

CREATE TABLE agendamentos
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    animal_id             BIGINT                                  NOT NULL,
    servico_id            BIGINT                                  NOT NULL,
    cliente_id            BIGINT                                  NOT NULL,
    data_hora_agendamento TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    status                VARCHAR(255)                            NOT NULL,
    observacoes           VARCHAR(255),
    CONSTRAINT pk_agendamentos PRIMARY KEY (id)
);


ALTER TABLE pessoas
    ADD CONSTRAINT uc_pessoas_cpf UNIQUE (cpf);

ALTER TABLE pessoas
    ADD CONSTRAINT uc_pessoas_email UNIQUE (email);

ALTER TABLE cargos
    ADD CONSTRAINT uc_cargos_cargo UNIQUE (cargo);

ALTER TABLE funcionarios
    ADD CONSTRAINT uc_funcionarios_crmv UNIQUE (crmv);


ALTER TABLE clientes
    ADD CONSTRAINT FK_CLIENTES_ON_PESSOA FOREIGN KEY (pessoa_id) REFERENCES pessoas (id);

ALTER TABLE funcionarios
    ADD CONSTRAINT FK_FUNCIONARIOS_ON_PESSOA FOREIGN KEY (pessoa_id) REFERENCES pessoas (id);

ALTER TABLE funcionarios
    ADD CONSTRAINT FK_FUNCIONARIOS_ON_CARGO FOREIGN KEY (cargo_id) REFERENCES cargos (id);

ALTER TABLE animais
    ADD CONSTRAINT FK_ANIMAIS_ON_CLIENTE FOREIGN KEY (cliente_id) REFERENCES clientes (pessoa_id);

ALTER TABLE servicos
    ADD CONSTRAINT FK_SERVICOS_ON_VETERINARIO FOREIGN KEY (veterinario_id) REFERENCES funcionarios (pessoa_id);

ALTER TABLE agendamentos
    ADD CONSTRAINT FK_AGENDAMENTOS_ON_ANIMAL FOREIGN KEY (animal_id) REFERENCES animais (id);

ALTER TABLE agendamentos
    ADD CONSTRAINT FK_AGENDAMENTOS_ON_CLIENTE FOREIGN KEY (cliente_id) REFERENCES clientes (pessoa_id);

ALTER TABLE agendamentos
    ADD CONSTRAINT FK_AGENDAMENTOS_ON_SERVICO FOREIGN KEY (servico_id) REFERENCES servicos (id);