CREATE TABLE agendamentos
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    animal_id             BIGINT                                  NOT NULL,
    servico_id            BIGINT                                  NOT NULL,
    cliente_id            BIGINT                                  NOT NULL,
    data_hora_agendamento TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    status                VARCHAR(255)                            NOT NULL,
    observacoes           VARCHAR(255),
    CONSTRAINT pk_agendamentos PRIMARY KEY (id)
);

CREATE TABLE animais
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome            VARCHAR(50)                             NOT NULL,
    especie         VARCHAR(255)                            NOT NULL,
    porte           VARCHAR(255)                            NOT NULL,
    raca            VARCHAR(50)                             NOT NULL,
    sexo            VARCHAR(255)                            NOT NULL,
    cor             VARCHAR(15),
    peso            DOUBLE PRECISION                        NOT NULL,
    castrado        BOOLEAN                                 NOT NULL,
    data_nascimento date                                    NOT NULL,
    observacao      VARCHAR(255),
    cliente_id      BIGINT,
    CONSTRAINT pk_animais PRIMARY KEY (id)
);

CREATE TABLE cargos
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    cargo   VARCHAR(255)                            NOT NULL,
    salario DECIMAL(10, 2)                          NOT NULL,
    CONSTRAINT pk_cargos PRIMARY KEY (id)
);

CREATE TABLE clientes
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome            VARCHAR(100)                            NOT NULL,
    cpf             VARCHAR(15)                             NOT NULL,
    data_nascimento date                                    NOT NULL,
    telefone        VARCHAR(20)                             NOT NULL,
    email           VARCHAR(100)                            NOT NULL,
    data_cadastro   date                                    NOT NULL,
    CONSTRAINT pk_clientes PRIMARY KEY (id)
);

CREATE TABLE funcionarios
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome            VARCHAR(100)                            NOT NULL,
    cpf             VARCHAR(15)                             NOT NULL,
    data_nascimento date                                    NOT NULL,
    telefone        VARCHAR(20)                             NOT NULL,
    email           VARCHAR(100)                            NOT NULL,
    data_admissao   date                                    NOT NULL,
    cargo_id        BIGINT                                  NOT NULL,
    crmv            VARCHAR(255),
    CONSTRAINT pk_funcionarios PRIMARY KEY (id)
);

CREATE TABLE servicos
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tipo           VARCHAR(255)                            NOT NULL,
    veterinario_id BIGINT                                  NOT NULL,
    valor          DECIMAL(10, 2)                          NOT NULL,
    CONSTRAINT pk_servicos PRIMARY KEY (id)
);

ALTER TABLE cargos
    ADD CONSTRAINT uc_cargos_cargo UNIQUE (cargo);

ALTER TABLE clientes
    ADD CONSTRAINT uc_clientes_cpf UNIQUE (cpf);

ALTER TABLE clientes
    ADD CONSTRAINT uc_clientes_email UNIQUE (email);

ALTER TABLE funcionarios
    ADD CONSTRAINT uc_funcionarios_cpf UNIQUE (cpf);

ALTER TABLE funcionarios
    ADD CONSTRAINT uc_funcionarios_crmv UNIQUE (crmv);

ALTER TABLE funcionarios
    ADD CONSTRAINT uc_funcionarios_email UNIQUE (email);

ALTER TABLE agendamentos
    ADD CONSTRAINT FK_AGENDAMENTOS_ON_ANIMAL FOREIGN KEY (animal_id) REFERENCES animais (id);

ALTER TABLE agendamentos
    ADD CONSTRAINT FK_AGENDAMENTOS_ON_CLIENTE FOREIGN KEY (cliente_id) REFERENCES clientes (id);

ALTER TABLE agendamentos
    ADD CONSTRAINT FK_AGENDAMENTOS_ON_SERVICO FOREIGN KEY (servico_id) REFERENCES servicos (id);

ALTER TABLE animais
    ADD CONSTRAINT FK_ANIMAIS_ON_CLIENTE FOREIGN KEY (cliente_id) REFERENCES clientes (id);

ALTER TABLE funcionarios
    ADD CONSTRAINT FK_FUNCIONARIOS_ON_CARGO FOREIGN KEY (cargo_id) REFERENCES cargos (id);

ALTER TABLE servicos
    ADD CONSTRAINT FK_SERVICOS_ON_VETERINARIO FOREIGN KEY (veterinario_id) REFERENCES funcionarios (id);